export const visitor_types = ["All visitor types", "Trade show visitors", "Consumers"];

export const show_types = ["Hybrid Show (On-site & Virtual)", "On-Site Show", "Virtual Show"];

export const participant_focus = ["B2B", "B2C", "B2B & B2C"];

export const industries = [
  "Advertising",
  "Laser Technology",
  "Marketing",
  "Technologies",
  "Franchising",
  "Inventions",
  "Aerospace",
  "Innovations",
  "Airport Construction",
  "Landscape Gardening",
  "Textile and Clothing Machinery",
  "Textile Cleaning",
  "Textiles (Clothing and Home Textiles",
  "Technical Textiles)",
  "Tourism",
  "Toys",
  "Games",
  "Computer Games",
  "Transport and Traffic",
  "Vehicles (Cars",
  "Commercial Vehicles",
  "Motorcycles",
  "Caravans",
  "Fisheries",
  "Parts & Accessories)",
  "Woodworking",
  "Furniture Production",
  "Livestock Farming",
  "Arts",
  "Agriculture and Forestry",
  "Antiques",
  "Boats",
  "Boat Accessories",
  "Books",
  "Prints",
  "Licenses",
  "Libraries",
  "Chemical and Petrochemical Industry",
  "City Sanitation",
  "Water Technology",
  "Waste Disposal",
  "Public Services",
  "Computer-Aided Engineering",
  "Factory Automation",
  "Measuring and Control",
  "Construction Technology",
  "Materials and Equipment",
  "Interior Fittings",
  "Clothing",
  "Fashion",
  "Accessories",
  "Consumer Electronics",
  "Multimedia",
  "Cosmetics",
  "Personal Hygiene",
  "Wellness",
  "Defense Technology",
  "Dental Medicine",
  "Dental Technology",
  "Design Services",
  "Electrical Engineering",
  "Electronics",
  "Energy (Conventional and Renewable)",
  "Environment and Climate Protection",
  "Facility Management",
  "Finance and Insurance Services",
  "Real Estate",
  "Export Promotion",
  "Floorings",
  "Food Processing and Packaging Machinery",
  "Food",
  "Beverage",
  "Luxury Foodstuff",
  "Foundry",
  "Metallurgy (Iron",
  "Non-ferrous Metals)",
  "Funerals and Religion",
  "Furniture",
  "Interior Design",
  "Garden and Pet",
  "Gifts",
  "Watches and Clocks",
  "Jewelry",
  "Crafts",
  "Special Occasion Party Items",
  "Hardware",
  "Tools",
  "Hotel and Catering",
  "Shop Fittings",
  "Household Goods and Appliances",
  "Ceramics",
  "Glassware",
  "Industrial Equipment",
  "Maintenance",
  "Information and Communication Technology",
  "Software",
  "Laboratory Technology",
  "Biotechnology",
  "Leather Processing and Show Machinery",
  "Leather",
  "Leather Goods",
  "Shoes",
  "Leisure",
  "Hobby",
  "DIY",
  "Lighting",
  "Lighting Technology",
  "Logistics",
  "Gears and Drivers",
  "Conveyance and Storage Technology",
  "Medical Engineering",
  "Health",
  "Pharmaceuticals",
  "Care",
  "Metalworking",
  "Welding Technology",
  "Mining",
  "Geodesy",
  "Geoinformation",
  "Music (Instruments",
  "Licenses)",
  "Nursery Equipment",
  "Children’s Clothing",
  "Office Equipment and Supplies",
  "Ophthalmic Optics",
  "Subcontracting",
  "Paper and Printing Industry",
  "Media Production",
  "Photography",
  "Broadcasting and Television Technology",
  "Film (Technology",
  "Licenses)",
  "Plastic and Rubber Processing",
  "Plumbing",
  "Heating",
  "Air Conditioning",
  "Refrigerators and Ventilation Technology",
  "Safety",
  "Disaster Control",
  "Shipbuilding",
  "Port Machinery",
  "Offshore Engineering",
  "Sporting Goods",
  "Surface Treatment Technology",
  "Teaching and Learning Aids",
  "Further and Continuing Education",
  "Business Start-up",
  "Human Resources Development",
  "Technical Optics",
];

export const countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Mali",
  "American Samoa",
  "Andorra",
  "Anguilla",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Antarctica",
  "Argentina",
  "Armenia",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Aruba",
  "Angola",
  "Australia",
  "Austria",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Azerbaijan",
  "Mongolia",
  "Antigua and Barbuda",
  "Montserrat",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Barbados",
  "Nauru",
  "Nepal",
  "Belarus",
  "Belgium",
  "Belize",
  "Netherlands",
  "Netherlands Antilles",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Benin",
  "Niger",
  "Bermuda",
  "Nigeria",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Niue",
  "Norfolk Island",
  "Northern Mariana Islands",
  "Botswana",
  "Bouvet Island",
  "Norway",
  "Brazil",
  "British Indian Ocean Territory",
  "Brunei Darussalam",
  "Bulgaria",
  "Oman",
  "Pakistan",
  "Palau",
  "Panama",
  "Burkina Faso",
  "Burundi",
  "Papua New Guinea",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Paraguay",
  "Peru",
  "Cape Verde",
  "Cayman Islands",
  "Philippines",
  "Central African Republic",
  "Chad",
  "Pitcairn",
  "Chile",
  "Poland",
  "China",
  "Portugal",
  "Congo",
  "Puerto Rico",
  "Christmas Island",
  "Qatar",
  "Cocos (Keeling Islands)",
  "Reunion",
  "Romania",
  "Colombia",
  "Russian Federation",
  "Comoros",
  "Rwanda",
  "Cook Islands",
  "Saint Kitts and Nevis",
  "Costa Rica",
  "Saint Lucia",
  "Saint Vincent and The Grenadines",
  "Samoa",
  "San Marino",
  "Cote D'Ivoire (Ivory Coast)",
  "Sao Tome and Principe",
  "Croatia (Hrvatska",
  "Saudi Arabia",
  "Cuba",
  "Cyprus",
  "Senegal",
  "Czech Republic",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovak Republic",
  "Denmark",
  "Slovenia",
  "Djibouti",
  "Solomon Islands",
  "Dominica",
  "Dominican Republic",
  "Somalia",
  "East Timor",
  "South Africa",
  "S. Georgia and S. Sandwich Isls.",
  "Spain",
  "Sri Lanka",
  "Ecuador",
  "St. Helena",
  "Egypt",
  "El Salvador",
  "St. Pierre and Miquelon",
  "Sudan",
  "Equatorial Guinea",
  "Suriname",
  "Svalbard and Jan Mayen Islands",
  "Swaziland",
  "Eritrea",
  "Sweden",
  "Estonia",
  "Switzerland",
  "Ethiopia",
  "Syria",
  "Falkland Islands (Malvinas)",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Faroe Islands",
  "Thailand",
  "Fiji",
  "Togo",
  "Tokelau",
  "Finland",
  "Tonga",
  "France",
  "France",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Metropolitan",
  "Turkmenistan",
  "French Guiana",
  "Turks and Caicos Islands",
  "French Polynesia",
  "French Southern Territories",
  "Gabon",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "Greece",
  "United Kingdom (Britain / UK)",
  "Gambia",
  "United States of America (USA)",
  "Georgia",
  "Germany",
  "US Minor Outlying Islands",
  "Ghana",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Gibraltar",
  "Vatican City State (Holy See)",
  "Guinea",
  "Venezuela",
  "Greenland",
  "Viet Nam",
  "Grenada",
  "Guadeloupe",
  "Virgin Islands (British)",
  "Guam",
  "Virgin Islands (US)",
  "Guatemala",
  "Wallis and Futuna Islands",
  "Guinea-Bissau",
  "Western Sahara",
  "Guyana",
  "Yemen",
  "Haiti",
  "Yugoslavia",
  "Zaire",
  "Heard and McDonald Islands",
  "Zambia",
  "Zimbabwe",
  "Honduras",
  "Hungary",
  "Hong Kong",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Japan",
  "Jamaica",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea (North)",
  "Korea (South)",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macau",
  "Macedonia",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
];

export const productCategories = [
  "Advertising",
  "Agricultural Machinery",
  "Aeronautics",
  "Agricultural Technology",
  "Agriculture",
  "Aids for the Disabled",
  "Foundry",
  "Franchising",
  "Air Conditioning Technology",
  "Airport Equipment",
  "Aluminium",
  "Aircraft Construction",
  "Angling Articles",
  "Fruit Growing",
  "Funeral Home Supplies",
  "Airport Construction",
  "Antiques",
  "Art",
  "Furniture",
  "Art Dealers",
  "Arts and Crafts",
  "Assembly Technology",
  "Furniture Accessories",
  "Furniture Manufacturing",
  "Astronautics",
  "Furs",
  "Amusement Parks",
  "Audio-Video Technology",
  "Automatic Identification",
  "Automobile Accessories",
  "Automobiles",
  "Games",
  "Garden Supplies",
  "Gas Gathering and Transport",
  "Bakery Equipment",
  "Gemstones",
  "Bakery Products",
  "Geodesy",
  "Geoinformation",
  "Gift Articles",
  "Ball Bearings",
  "Glass Technology",
  "Bank Technology",
  "Glassware",
  "Golf Equipment",
  "Goods Transport",
  "Graphic Industry",
  "Bathroom Fittings",
  "Beverages",
  "Bicycles",
  "Biotechnology",
  "Hairdressers’ Supplies",
  "Boat Accessories",
  "Hardware",
  "Boats",
  "Boiler Manufacturing",
  "Books (including Licenses)",
  "Brewing Technology",
  "Building Ceramics",
  "Building Cleaning",
  "Hats",
  "Health",
  "Building Machinery",
  "Building Materials",
  "Building Materials Machinery",
  "Butchers’ Equipment",
  "Cable Manufacturing",
  "CAD",
  "CAM",
  "Camping",
  "Heating Technology",
  "Hi-Fi",
  "Hobby",
  "Home Textiles",
  "Hospital Equipment",
  "Car Workshop Equipment",
  "Hotel Fittings",
  "Caravans",
  "Household Appliances",
  "Cardboard Manufacturing",
  "Household Goods",
  "Hunting Equipment",
  "Care",
  "Industrial Equipment",
  "Industrial Fittings (Chemical Industry)",
  "Carpets",
  "Industrial Fittings (Energy Industry)",
  "Industrial Fittings (Environmental)",
  "Industrial Fittings (Food and Beverages)",
  "Catering",
  "Industrial Fittings (Public Services)",
  "Industrial Safety",
  "Ceramics",
  "Information Technology",
  "Ceramics Manufacturing",
  "Insurances",
  "Interior Fittings",
  "Cereal Agriculture",
  "Internet",
  "Cereals Processing",
  "Inventions",
  "Chemicals Industry",
  "Investments",
  "Iron",
  "Children’s Clothing",
  "Jewelry",
  "CIM",
  "Kitchens",
  "Knitwear",
  "Laboratory Technology",
  "Landscaping",
  "Cinema (Technology",
  "Large Kitchen Equipment",
  "Licenses)",
  "Laser Technology",
  "City Sanitation",
  "Learning Aids",
  "Leather",
  "Leather Clothing",
  "Leather Goods",
  "Leather Processing Machines",
  "Leisure",
  "Climate Protection",
  "Libraries",
  "Licensing",
  "Clocks and Watches",
  "Lift Construction",
  "Clothing",
  "Lifts",
  "Light Industry",
  "Clothing Machinery",
  "Lighting",
  "Clothing Textiles",
  "LIghting Technology",
  "Coal Mining",
  "Livestock Breeding",
  "Coffee",
  "Coffins",
  "Livestock Farming",
  "Coil Technology",
  "Logistics",
  "Coins",
  "Luxury Foodstuff",
  "Luxury Goods",
  "Machine Tools",
  "Commercial Fishing",
  "Commercial Vehicles",
  "Communal Services",
  "Magazines",
  "Maintenance",
  "Marine Technology",
  "Marketing",
  "Markings",
  "Communication Technology",
  "Computer Games",
  "Materials Handling",
  "Computer Graphics",
  "Computer Science",
  "Computer Technology",
  "Computer-Aided Engineering",
  "Congress Industry",
  "Confectionery",
  "Measurement Technology",
  "Metal Processing",
  "Metallurgy",
  "Construction Materials",
  "Microsystem Technology",
  "Construction of Chemical Apparatus",
  "Consumer Electronics",
  "Consumer Goods",
  "Continuing Education",
  "Control Equipment",
  "Control Systems",
  "Conveyor Technology",
  "Corrosion Protection",
  "Minerals",
  "Cosmetics",
  "Cruise Ships",
  "Mining",
  "Dairy Products",
  "Mobile Telephony",
  "Dairy Technology",
  "Decoration",
  "Defense",
  "Defense Technology",
  "Dental Medicine",
  "Dental Technology",
  "Design",
  "Disaster Control",
  "Do-It-Yourself Supplies",
  "Doors",
  "Drink Manufacturing",
  "Electrical Engineering",
  "Drive Technology",
  "E-Commerce",
  "Electronics",
  "Model Engineering",
  "Energy Management",
  "Environmental Technology",
  "Equestrian Sport",
  "Event Technology",
  "Export Promotion",
  "Fabrics",
  "Facility Management",
  "Fashion",
  "Fashion Accessories",
  "Feedback Control Systems",
  "Film (Technology",
  "Licenses)",
  "Modernization",
  "Fire Protection",
  "Firefighting",
  "Fish and Seafood",
  "Flooring",
  "Flowers",
  "Fluid Technology",
  "Food",
  "Food Processing Machines",
  "Motorcycles",
  "Forestry",
  "Mountaineering Equipment",
  "Multimedia",
  "Mushrooms",
  "Musical Instruments",
  "Natural Stones",
  "New Materials (Industrial Equipment)",
  "Non-Ferrous Metals",
  "Nuclear Energy",
  "Nursery Equipment",
  "Office Equipment",
  "Office Supplies",
  "Offshore Technology",
  "Oil Hydraulics",
  "Oil Production and Transport",
  "Olericulture",
  "Ophthalmic Optics",
  "Opto-Electronics",
  "Packaging Machines",
  "Packaging Materials Manufacturing",
  "Paper Industry",
  "Paper Production and Processing",
  "Passenger Transportation",
  "Perfumery",
  "Personal Protection",
  "Pet Supplies",
  "Petrochemicals",
  "Petrol Station Supplies",
  "Pets",
  "Pharmaceuticals",
  "Photography (Technology",
  "License)",
  "Plants",
  "Plastic Processing",
  "Pneumatics",
  "Porcelain",
  "Port Construction",
  "Port Installations",
  "Postage Stamps",
  "Poultry Breeding",
  "Powder Technology",
  "Printed Circuit Board Technology",
  "Printing Industry",
  "Printing Machines",
  "Prints",
  "Production Automation",
  "Railway Industry",
  "Railway Technology",
  "Real Estate",
  "Recycling",
  "Refrigeration Technology",
  "Rehabilitation",
  "Renewable Energy",
  "Renovation",
  "Rental Services",
  "Restaurant Fittings",
  "Restoration",
  "Road Construction",
  "Robotics",
  "Roofing",
  "Rubber Processing",
  "Sanitary Engineering",
  "Sanitary Products",
  "School Equipment",
  "School Supplies",
  "Scientific Equipment",
  "Secondary Raw Materials",
  "Security Technology",
  "Semiconductor Technology",
  "Servicing",
  "Sewage Technology",
  "Sheet Metal Processing",
  "Sheet Music",
  "Shipbuilding",
  "Shoe Machinery",
  "Shoes",
  "Shop Fittings",
  "Showmen’s Trade",
  "Silk",
  "Solar Energy",
  "Sound Engineering",
  "Spectacles",
  "Spirits",
  "Sports",
  "Sports Equipment",
  "Sportswear",
  "Stage Technology",
  "Stationery",
  "Steel",
  "Storage Technology",
  "Subcontracting",
  "Sun Blinds",
  "Surface Treatment Technology",
  "Surveillance Technology",
  "Swimming Pool Technology",
  "Synthetic Fibres",
  "Tea",
  "Teaching Aids",
  "Technical Optics",
  "Technical Textiles",
  "Technologies",
  "Telecommunications",
  "Television Technology",
  "Test Engineering",
  "Textile Cleaning",
  "Textile Machinery",
  "Textiles",
  "Therapeutic Technology",
  "Thermo Process Technology",
  "Threads & Yarns",
  "Tobacco Products",
  "Toiletries",
  "Tombstones",
  "Tools",
  "Tourism",
  "Toys",
  "Traffic Equipment",
  "Transport Means",
  "Travel",
  "Trendy Sports",
  "Tube Manufacturing",
  "TV Devices",
  "Tyres",
  "Urban and Regional Planning",
  "Valves",
  "Vegetarian Food",
  "Vending Machines",
  "Ventilation Technology",
  "Viniculture",
  "Waste Disposal",
  "Waste Technology",
  "Water Sports",
  "Water Supply",
  "Water Technology",
  "Welding Technology",
  "Wellness",
  "Windows",
  "Wine",
  "Winery Equipment",
  "Winery Industry",
  "Winter Sports",
  "Wire Manufacturing",
  "Wire Processing",
  "Woodworking",
  "Workwear Clothing",
];
